services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-playto_pay}
      POSTGRES_USER: ${POSTGRES_USER:-playto}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      APP_DOMAIN: ${APP_DOMAIN:?APP_DOMAIN is required}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

  web:
    build: .
    restart: unless-stopped
    command: bin/start-web
    expose:
      - "8000"
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://${POSTGRES_USER:-playto}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-playto_pay}
      REDIS_URL: redis://redis:6379/0
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY is required}
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:?CORS_ALLOWED_ORIGINS is required}
      RUN_DEMO_SEED_ON_DEPLOY: ${RUN_DEMO_SEED_ON_DEPLOY:-false}
      DEMO_MERCHANT_ID: ${DEMO_MERCHANT_ID:-}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    restart: unless-stopped
    command: bin/start-worker
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-playto}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-playto_pay}
      REDIS_URL: redis://redis:6379/0
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY is required}
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  beat:
    build: .
    restart: unless-stopped
    command: bin/start-beat
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-playto}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-playto_pay}
      REDIS_URL: redis://redis:6379/0
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY is required}
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
